// Embeds schema.sql into a TypeScript module so the runtime never depends on
// the filesystem layout (dev server, next start, standalone output, seed script).
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const sql = readFileSync(resolve(root, "src/lib/db/schema.sql"), "utf8");

if (sql.includes("`") || sql.includes("${")) {
  throw new Error("schema.sql contains characters that break template literals");
}

writeFileSync(
  resolve(root, "src/lib/db/schema.generated.ts"),
  `// AUTO-GENERATED by scripts/gen-schema.mjs — edit src/lib/db/schema.sql instead.\n` +
    `/* eslint-disable */\nexport const SCHEMA_SQL = \`${sql}\`;\n`,
);
console.log("schema.generated.ts written (%d bytes)", sql.length);
